# 第 6 课 Python 科学计算与 NumPy 软件包

## 学习任务
本周是第 8 周。请⼀边阅读教材⼀边完成课程测验任务，同时⼀边阅读⼀边完成以下⾮上机题任务。课
程测验得分将构成平时成绩 (占期末总评 40%)；所有⾮上机题将构成期末闭卷考试 (占期末总评 60%)
的题库。所以请务必认真对待学习任务，不能按时完成任务者后果⾃负。

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

### 1 阅读
阅读教材[ “The Scientific Libraries: Python for Scientific Computing”](https://python-programming.quantecon.org/need_for_speed.html) ⼀节，学习有关 Python 科学计
算的基础知识。


### <font color = red>2 简答题
请简述我们使⽤各种 Python 科学计算⽅⾯的软件包 (package) ⽽不是纯 Python 的两个原因

原因
- 1.各种各样的开源python库（et...scientific libraries）可以满足我们很多的需求，比让我们自己根据需求从底层开始编程要方便快捷的多，可以大幅度的提升效率（和社区用户共同提高，体现了计算机语言世界的自由平等、开放共享精神）

- 2.纯 Python 虽然灵活而快捷，但python作为高级语言在速度上远不如某些语言（如C语言等），同样是为了提高效率

### 3 简答题
请简要介绍 Python 五⼤科学计算软件包各⾃的⽤途。

科学 Python 库中的五大类是

- NumPy
- SciPy
- Matplotlib
- Pandas 
- Numba

1. NumPy的本质基础是提供基本的数组数据类型(想想向量和矩阵)和作用于这些数组的函数(例如，矩阵乘法)
 
2. Scipy 基于 NumPy，添加了科学中常用的各种数学方法(插值、优化、求根等)

3. Matplotlib 用于生成图形，重点是绘制存储在 NumPy 数组中的数据

4. Pandas 为实验等实操工作提供格式类型处理和功能(例如操作数据)

5. Numba 通过 JIT 编译加速执行

###  <font color = red>4 简答题
Python 作为⼀种对⼈类友好的 (optimized for human) ⾼层语⾔ (high-level language)，相⽐于对机器
友好的 (optimized for machine) 底层语⾔ (low-level language) (如 C、Fortran)，在运⾏时 (runtime)
能够替程序员完成哪两类繁重⼯作？

#### 答
1. 使用前先指定变量的类型
2. 分配和释放内存


###  <font color = red>5 简答题
像 Python 这样的⾼层语⾔ (high-level language)，相⽐于像 C、Fortran 这样的底层语⾔ (low-level
language)，优势和劣势分别是什么？

#### 答

1. 优势
    - 与低级语言相比，Python 通常编写得更快，更不容易出错，更容易调试。
    
2. 劣势
    - Python 比 c 或 Fortran 等语言更难优化（更难转化成快速的机械语言），Python 的标准实现(称为 CPython)不能与 c 或 Fortran 等编译语言的速度相匹配。

### 6 简答题
科研⼈员应该使⽤ Python ⽽不是 C、Fortan 进⾏编程的两个重要原因是什么？

### 答
原因：
1. 对于任何给定的程序来说，只有相对较少的代码行对运行时间有需求，也就是说一般情况下python的运行效率足够了，在这些情况下用 Python 这样的高效语言编写效率更高


2. 即使有代码对运行时间（速度）有需求，也可以用python库来协助提速，很多情况下都可以使用 Python 的科学库实现与 c 或 Fortran 相同的速度。

### <font color = red>7 简答题
像 `a + b` 这样的简单 Python 代码都需要 Python 运⾏时 (runtime) 执⾏⼤量的⼯作，为什么？

### 答
在这个语句中，解释器必须先知道要调用哪个操作，如果` a` 和` b `是字符串，那么` a + b `需要字符串连接；如果 `a `和` b `是列表，那么` a + b` 需要列表连接；Python 必须检查对象的类型，然后调用正确的操作，这都需要执行大量的工作

### <font color = red>8 简答题
Python 列表 (list) 不同于 C 数组 (array) 的地⽅在于，Python 列表 (list) ⾥的元素 (element) 保存的不
是实际的数据，⽽是什么？

### 答
- 在标准的 Python 实现(CPython)中，列表元素被放置在某种意义上是连续的内存位置中
然而，这些列表元素更像是指向数据的指针（调用时指向数据内存地址），而不是实际的数据。


### <font color = red>9 简答题
使⾼层语⾔ (high-level language) 的数值计算⼯作⼤⼤提速的⼀种办法叫做向量化 (vectorization)，始
于 Matlab。请简要介绍向量化 (vectorize) ⽅法的核⼼思想。

### 答
其核心思想是将数组的处理操作批量发送到预编译好的、高效的保存在本地的本机代码中

### 10 简答题
假设已进⾏过如下 import 。

In [ ]:
import random
import numpy as np

以下⼀段 Python 代码在运⾏时 (runtime) 将⽐较低效。请写出能够达到同样效果的更加⾼效的向量化
(vectorized) 代码，借助于 numpy 。

In [ ]:
n=1_000_000

In [4]:
%%time
y = 0
for i in range(1_000_000):
    x = random.uniform(0, 1)
    y += x**2

Wall time: 648 ms


In [11]:
%%time
n=1_000_000
x = np.random.uniform(0, 1, n)
y = np.sum(x**2)
#y = sum(x**2) 120ms

Wall time: 27.3 ms


### 11 简答题
如下 Python 代码使⽤了 numpy 的向量化 (vectorization) 技术来计算 y 。

In [15]:
%%time
import numpy as np
n = 1_000_000
x = np.random.uniform(0, 1, n)
y = np.sum(x**2)
y

Wall time: 20.9 ms


333970.3828678028

在计算过程中，将发⽣哪三次向量化的批量操作 (batch operation)？

#### 三个基本操作

1. 计算出n个uniform随机数
2. 将每个随机数平方
3. 求这些随机数平方后的和

### <font color = red>12 简答题
寻找⼀个函数 在⼀个定义域 上的最⼤值，有许多数值优化 (numerical optimization) ⽅法可选择，
其中最基本、最⽆知 (naive) 的⼀种⽅法叫做⽹格搜索 (grid search)。请简要介绍⽹格搜索 (grid
search) ⽅法的基本思想。

#### 答
将定义域按照一定的精确度用网格划分为大量的小区间，并求网格格点的函数值，通过穷举搜索：在所有候选的参数（格点）选择中循环遍历，尝试每一种可能，最终得到逼近定义域最值得一个估计最值

### 13 简答题
假设已经进⾏过如下`import `和 `def `。

In [17]:
import numpy as np
def f(x, y):
    return np.cos(x**2 + y**2) / (1 + x**2 + y**2)

以下⼀段 Python 代码在运⾏时 (runtime) 将⽐较低效。请写出能够达到同样效果的更加⾼效的向量化
(vectorized) 代码，借助于` numpy` 。

In [21]:
%%time
grid = np.linspace(-3, 3, 1000)
m = -np.inf
for x in grid:
    for y in grid:
        z = f(x, y)
        if z > m:
            m = z

Wall time: 3.32 s


### 答

In [22]:
%%time

x, y = np.meshgrid(grid, grid)
np.max(f(x, y))

Wall time: 49.2 ms


0.9999819641085747

### 14 简答题
使⽤ `numpy `进⾏向量化 (vectorized) 计算固然能够提⾼计算速度，但有哪两处缺点？为什么会有这些
缺点？

### 答
##### 缺点
1. 它可能是高度内存密集型的（短时间内对内存和计算机资源有大量需求）
2. 不是所有的算法都可以向量化，所以有时候使用时需要回到loops过程

##### 原因
1. 向量化计算倾向于创建许多中间数组直到计算完成，需要持续消耗大量的资源

2. numpy库可用的函数有限，不能满足我们无上限的需求

### 15 阅读
阅读教材 [“The Scientific Libraries: NumPy”](https://python-programming.quantecon.org/numpy.html) ⼀节，学习有关 numpy 软件包 (package) 的基础知识。

### <font color = red>16 简答题
numpy 软件包 (package) 的主要⽬的是解决什么问题？其提供的最重要的⼀个数据类型 (data type) 是
什么？

#### 答：
1. 主要解决的问题是python对数组的处理的效率不足的问题，它可以帮助我们进行大量的、快速的数组处理

2. Numpy 定义的最重要的结构是一个数组数据类型，正式名称为 NumPy.ndarray。

### <font color = red>17 简答题
`numpy`数组 (array) 与 Python 列表 (list) ⽐较相似，但有两处重要的不同，分别是什么？

#### 两处重要的不同

1. 数据必须是同质的（它所含有的元素的类型相同）


2. 数据类型有限制，必须是numpy提供的dtypes，这些类型中最重要、常用的是:

    - 64位浮点数
    - 64位整数
    - 布尔值（8位，True或者False）

还有 dtype 来表示复数、无符号整数等。



### 18 简答题
#### 以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [28]:
import numpy as np
z = np.zeros(6)

z.shape

(6,)

#### 以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [29]:
import numpy as np
z = np.zeros((2, 3))
z
z.shape

array([[0., 0., 0.],
       [0., 0., 0.]])

(2, 3)

#### 以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [33]:
import numpy as np
#z = np.zeros(2, 3)
#z.shape
# data type not understood

    #与题目无关
    ###z = np.zeros(10)
    z.shape
    z
    z.shape = (10, 1)
    z

### 19 简答题
要⽣成⼀个 的 numpy 数组 (array)，数组 (array) ⾥所有元素 (element) 的值都为1 ，应该键⼊
什么代码

In [38]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 20 简答题
请简要介绍` np.linspace` 函数的⽤途，并回答` np.linspace(-1, 1, 5)` 将返回什么结果。

#### 用途：生成等间距的数字网格

In [42]:
np.linspace(-1, 1, 5)#从-1到1，等间距生成五个值

array([-1. , -0.5,  0. ,  0.5,  1. ])

### 21 简答题
要⽤ numpy ⽣成⼀个$3*3$ 的单位矩阵

\begin{bmatrix} 1&0&0 \\0&1&0\\ 0&0&1 \end{bmatrix}


应该键⼊什么代码？

In [44]:
np.identity(3)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 22 简答题
要⽤ numpy ⽣成如下矩阵

应该键⼊什么代码？

\begin{bmatrix} 3&1&2 \\ 1&4&2 \end{bmatrix}

In [46]:
np.array([[3,1,2],[1,4,2]])

array([[3, 1, 2],
       [1, 4, 2]])

### 23 简答题
已知

In [49]:
m = np.array([[2, 1, 3], [2, 1, 4]]); m
#array([[2, 1, 3],
#[2, 1, 4]])

array([[2, 1, 3],
       [2, 1, 4]])

要从` m `中切取出矩阵

\begin{bmatrix} 1&3 \\ 1&4 \end{bmatrix}

#### 应该键⼊什么代码？


In [53]:
m[:,1:]

array([[1, 3],
       [1, 4]])

### 25 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [59]:
import numpy as np
z = np.linspace(2, 4, 5)
d = np.array([0, 1, 0, 10, 0], dtype=bool)
z[d]

array([2.5, 3.5])

### 26 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

另一个值得了解的方法是 searchsorted ()。

如果 z 是一个非递减数组，那么 z.searchsorted (a)返回的第一个>=a的z里面元素的索引



In [62]:
import numpy as np
z = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
z.searchsorted(3)

2

### 27 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [63]:
import numpy as np
a = np.array([4, 3, 2, 1])
b = np.array([2, 3, 4, 5])
a * b

array([8, 9, 8, 5])

### 28 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [64]:
import numpy as np
a = np.eye(3)
a + 2

array([[3., 2., 2.],
       [2., 3., 2.],
       [2., 2., 3.]])

### 29 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [65]:
import numpy as np
a = np.array([[1, 0], [0, 1]])
b = np.array([[2, 2], [2, 2]])
a * b

array([[2, 0],
       [0, 2]])

### 30 简答题
已知

In [66]:
import numpy as np
a = np.array([[1, 0], [0, 1]])
b = np.array([[2, 2], [2, 2]])

要计算 `a` 、`b `两矩阵的矩阵乘积 (matrix multiplication)，应该键⼊什么代码？

In [68]:
a@b

array([[2, 2],
       [2, 2]])

### 31 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [74]:
import numpy as np
a = np.array([4, 2, 3])
b = a#只传递指针
b[0] = 1
a

array([1, 2, 3])

### 32 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [75]:
import numpy as np
a = np.array([4, 2, 3])
b = a.copy()
b[0] = 1
a

array([4, 2, 3])

### 33 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [77]:
import numpy as np
a = np.array([9, 4, 16])
(np.sqrt(a) - 1)**2

array([4., 1., 9.])

### 34 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [78]:
import numpy as np
a = np.array([9, 4, 16])
np.where(a < 10, 1, 0)

array([1, 1, 0])

### 35 简答题
以下定义的函数 `f `只能作⽤于单个浮点数` x` ，

In [80]:
def f(x):
    return 1 if x < 10 else 0

键⼊什么代码可以使`f`能够同样作⽤于浮点数所构成的数组 (array)？

#### 答

#### 第一种方法

In [90]:
x = np.array([[1,0],[3,4]])
x

array([[1, 0],
       [3, 4]])

In [91]:
def f(x):
    return np.where(x > 0, 1, 0)  # Insert 1 if x > 0 true, otherwise 0
f(x)

array([[1, 0],
       [1, 1]])

#### 第二种方法

In [ ]:
def f(x):
    return 1 if x < 10 else 0

In [92]:
f = np.vectorize(f)
x = np.array([[1,0],[3,4]])
x
f(x)

array([[1, 0],
       [3, 4]])

array([[1, 0],
       [1, 1]])

### 36 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [93]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 2, 0])
a == b

array([ True,  True, False])

### 37 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [94]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 2, 0])
a > b

array([False, False,  True])

### 38 简答题
以下代码运⾏后最后⼀个表达式将计算出什么结果？

In [95]:
import numpy as np
z = np.array([ 0. , 2.5, 5. , 7.5, 10. ])
z[z > 3]

array([ 5. ,  7.5, 10. ])

### 39 简答题
运⾏过以下代码之后，

In [96]:
import numpy as np
a = np.array([[1, 2], [3, 4]])

键⼊什么代码可以计算⽅阵 a 的⾏列式 (determinant)？

In [98]:
np.linalg.det(a)

-2.0000000000000004

### 40 简答题
运⾏过以下代码之后

In [101]:
import numpy as np
a = np.array([[1, 2], [3, 4]])

#### 键⼊什么代码可以计算⽅阵 a 的逆矩阵 (inverse matrix)？

In [103]:
np.linalg.inv(a) 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

<font color = red>
####  这一章有一个小技巧看一个定义的函数是不是矢量化函数：有没有逐个元素的显式循环